### PR TITLE
[Exploit Fix] F9 Crouch Toggle & Vehicle Control Exploit Fixes

### LINKED ISSUE #1602: F9 Issues
`if u flip ur car and f9, a+d wiggle lets u flip ur car`
`if you alt w crouch then f9 ur walk style`

### PR DESCRIPTION
**Pull request by maxgestic**
- Fixes Being able to control flipped and in-air vehicles with f9 menu open
- Fixes toggle crouching when aiming when crouching, then setting a walkstyle

Closes #1602

### CODE REVIEW

File: resources/dpemotes/Client/EmoteMenu.lua [hunk 1]
```diff
@@ -253,10 +254,40 @@ function AddFaceMenu(menu)
     end
 end
 
+function vehicleDisalow()
```
Comment (minipunch) [inline resources/dpemotes/Client/EmoteMenu.lua:257]:
```suggestion
function vehicleDisallowRollover()
```

File: resources/dpemotes/Client/EmoteMenu.lua [hunk 2]
```diff
@@ -253,10 +254,40 @@ function AddFaceMenu(menu)
...
+  local disalow = false
+  local ped = PlayerPedId()
+  if IsPedInAnyVehicle(ped, true) then
+    local vehicle = GetVehiclePedIsIn(ped, false)
+    local roll = GetEntityRoll(vehicle)
+    if ((roll > 75.0 or roll < -75.0) and GetEntitySpeed(vehicle) < 2) or IsEntityInAir(vehicle) then
+        disalow = true
+    end
+  end
+  return disalow
```
Comment (minipunch) [inline resources/dpemotes/Client/EmoteMenu.lua:267]:
```suggestion
  return disallow
```

**Review by minipunch — APPROVED** [review]
