### PR TITLE
Fixed false anticheese flags for warehouses

### LINKED ISSUE #1654: warehouse heist triggering false anti cheat flags
happens when entering/exiting the warehouse during a heist

### PR DESCRIPTION
**Pull request by DatBoiWeep**
Fixes #1654

Added warp locations into `_anticheese` to prevent spam for staff

### CODE REVIEW

**Review by minipunch — COMMENTED** [review]
did u actually test this on ur test server and confirm it stopped the false alerts?

**Comment by DatBoiWeep** [comment]
> did u actually test this on ur test server and confirm it stopped the false alerts?

yes, I enabled ` _anticheese` and `usa_utils` to make sure it worked

**Comment by minipunch** [comment]
swagged out

**Comment by minipunch** [comment]
I will say a better fix would be to automatically pull all the locations for warp points and load it that way

Otherwise any time we add or remove one we also need to update this separate list :(

**Review by minipunch — CHANGES_REQUESTED** [review]
see comments above, he said he will make an export to get all locations

**Comment by DatBoiWeep** [comment]
**Update:** Tested, turns out we can't use a server export on a client file. So I had to use the client av-warehouse to actually make the export work.

File: resources/_anticheese/cl_anticheese.lua [hunk 1]
```diff
@@ -782,6 +782,12 @@ function isAtAWarpPoint(x, y, z)
 			return true
 		end
 	end
+	local warehousecoords = exports["av-warehouse"]:getWarehouseLocations()
```
Comment (minipunch) [inline resources/_anticheese/cl_anticheese.lua:785]: exports are CPU intensive to call

so you should move this somewhere where it only runs one time and not every time this function is run

File: resources/av-warehouse/client/main.lua [hunk 2]
```diff
@@ -391,4 +391,12 @@ function alertPolice(coords)
 	local lastStreetHASH = GetStreetNameAtCoord(x, y, z)
 	local lastStreetNAME = GetStreetNameFromHashKey(lastStreetHASH)
 	TriggerServerEvent('911:call', x, y, z, "Warehouse burglary alarm triggered (" .. lastStreetNAME .. ")", "Warehouse Burglary")
-end
\ No newline at end of file
+end
+
+exports("getWarehouseLocations", function()
+	local coords = {
+		[1] = {x = coordx, y = coordy, z = coordz},
```
Comment (minipunch) [inline resources/av-warehouse/client/main.lua:398]: ????

i don't understand this list of coordinates lol

**Review by minipunch — CHANGES_REQUESTED** [review]

File: resources/av-warehouse/client/main.lua (hunk 2 above)
Comment (minipunch) [reply resources/av-warehouse/client/main.lua:398]: shouldn't this be the actual list of locations

Comment (minipunch) [reply resources/av-warehouse/client/main.lua:398]: oh right this is using the set coord

maybe it would be better to grab ALL the locations at once instead here

File: resources/_anticheese/cl_anticheese.lua (hunk 1 above)
Comment (DatBoiWeep) [reply resources/_anticheese/cl_anticheese.lua:785]: ooooooh. Very well, I shall relocate that bad boi

**Comment by DatBoiWeep** [comment]
pls re-examine. It has been tested and works

I also could not for the life of me figure out how to bring the coords from the `server.lua` to the `anticheese` client file as an export.

**Comment by minipunch** [comment]
> I also could not for the life of me figure out how to bring the coords from the `server.lua` to the `anticheese` client file as an export.

just need to use `TriggerServerCallback` to fetch the info inside the get locations export

**Comment by minipunch** [comment]
did it 4 u [245d266](https://github.com/minipunch/usarealismrp-fxserver/pull/1661/commits/245d2660ad53700599b9bd273e47741e5d15429a)

**Review by minipunch — APPROVED** [review]
